"""
MCP Server Builder Module (Meta-Loop)
Uses Bob to generate custom MCP servers, then uses those servers with Bob
"""
from datetime import datetime
from typing import Dict, List, Optional
from pydantic import BaseModel


class MCPTool(BaseModel):
    """Definition of an MCP tool"""
    name: str
    description: str
    parameters: Dict[str, str]  # param_name -> type
    example_usage: str


class MCPServerSpec(BaseModel):
    """Specification for generating an MCP server"""
    name: str
    description: str
    tools: List[MCPTool]
    language: str = "python"  # "python" or "typescript"


class GeneratedMCPServer(BaseModel):
    """A generated MCP server"""
    id: str
    spec: MCPServerSpec
    code: str
    tests: str
    docs: str
    generated_at: int  # unix epoch ms
    status: str  # "generated", "deployed", "active"


class MCPServerBuilder:
    """Uses Bob to generate custom MCP servers"""
    
    def __init__(self):
        self.servers: Dict[str, GeneratedMCPServer] = {}
    
    async def generate_mcp_server(
        self,
        spec: MCPServerSpec
    ) -> GeneratedMCPServer:
        """Generate a complete MCP server with tests and docs"""
        server_id = f"mcp_{spec.name}_{int(datetime.utcnow().timestamp())}"
        
        # Simulate Bob generating the server
        code = self._generate_server_code(spec)
        tests = self._generate_tests(spec)
        docs = self._generate_docs(spec)
        
        server = GeneratedMCPServer(
            id=server_id,
            spec=spec,
            code=code,
            tests=tests,
            docs=docs,
            generated_at=int(datetime.utcnow().timestamp() * 1000),
            status="generated"
        )
        
        self.servers[server_id] = server
        return server
    
    def _generate_server_code(self, spec: MCPServerSpec) -> str:
        """Generate MCP server code"""
        if spec.language == "python":
            return self._generate_python_server(spec)
        else:
            return self._generate_typescript_server(spec)
    
    def _generate_python_server(self, spec: MCPServerSpec) -> str:
        """Generate Python MCP server"""
        tools_code = "\n\n".join([
            f'''@server.call_tool()
async def {tool.name}({", ".join(f"{k}: {v}" for k, v in tool.parameters.items())}) -> str:
    """
    {tool.description}
    
    Example: {tool.example_usage}
    """
    # Implementation here
    return f"Executed {tool.name}"'''
            for tool in spec.tools
        ])
        
        return f'''"""
{spec.description}
Generated by Bob MCP Server Builder
"""
from mcp.server import Server
from mcp.server.stdio import stdio_server

server = Server("{spec.name}")

{tools_code}

async def main():
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options()
        )

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
'''
    
    def _generate_typescript_server(self, spec: MCPServerSpec) -> str:
        """Generate TypeScript MCP server"""
        tools_code = "\n\n".join([
            f'''server.tool("{tool.name}", "{tool.description}", {{
  {", ".join(f'{k}: "{v}"' for k, v in tool.parameters.items())}
}}, async (params) => {{
  // Implementation here
  return `Executed {tool.name}`;
}});'''
            for tool in spec.tools
        ])
        
        return f'''/**
 * {spec.description}
 * Generated by Bob MCP Server Builder
 */
import {{ Server }} from "@modelcontextprotocol/sdk/server/index.js";
import {{ StdioServerTransport }} from "@modelcontextprotocol/sdk/server/stdio.js";

const server = new Server({{
  name: "{spec.name}",
  version: "1.0.0"
}});

{tools_code}

async function main() {{
  const transport = new StdioServerTransport();
  await server.connect(transport);
}}

main().catch(console.error);
'''
    
    def _generate_tests(self, spec: MCPServerSpec) -> str:
        """Generate tests for the MCP server"""
        test_cases = "\n\n".join([
            f'''def test_{tool.name}():
    """Test {tool.name} tool"""
    result = await server.call_tool("{tool.name}", {{{", ".join(f'"{k}": "test"' for k in tool.parameters.keys())}}})
    assert result is not None
    assert "Executed" in result'''
            for tool in spec.tools
        ])
        
        return f'''"""
Tests for {spec.name} MCP Server
Generated by Bob
"""
import pytest

{test_cases}
'''
    
    def _generate_docs(self, spec: MCPServerSpec) -> str:
        """Generate documentation for the MCP server"""
        tools_docs = "\n\n".join([
            f'''### `{tool.name}`

{tool.description}

**Parameters:**
{chr(10).join(f"- `{k}` ({v})" for k, v in tool.parameters.items())}

**Example:**
```
{tool.example_usage}
```'''
            for tool in spec.tools
        ])
        
        return f'''# {spec.name}

{spec.description}

## Installation

```bash
# Add to Bob's MCP config
{{
  "mcpServers": {{
    "{spec.name}": {{
      "command": "python",
      "args": ["{spec.name}_server.py"]
    }}
  }}
}}
```

## Tools

{tools_docs}

## Generated by Bob

This MCP server was generated using the Bob MCP Server Builder.
'''
    
    def get_server(self, server_id: str) -> Optional[GeneratedMCPServer]:
        """Get generated server by ID"""
        return self.servers.get(server_id)
    
    def list_servers(self) -> List[GeneratedMCPServer]:
        """List all generated servers"""
        return list(self.servers.values())
    
    def deploy_server(self, server_id: str) -> bool:
        """Mark server as deployed"""
        server = self.servers.get(server_id)
        if server:
            server.status = "deployed"
            return True
        return False


# Pre-built example specs
EXAMPLE_SPECS = [
    MCPServerSpec(
        name="hipaa_compliance",
        description="HIPAA Compliance Checker MCP Server",
        tools=[
            MCPTool(
                name="check_phi_exposure",
                description="Check if code exposes Protected Health Information",
                parameters={"file_path": "str", "code": "str"},
                example_usage='check_phi_exposure(file_path="patient.py", code="...")'
            ),
            MCPTool(
                name="audit_access_logs",
                description="Audit access logs for HIPAA compliance",
                parameters={"log_file": "str", "days": "int"},
                example_usage='audit_access_logs(log_file="access.log", days=30)'
            ),
        ],
        language="python"
    ),
    MCPServerSpec(
        name="api_documentation",
        description="Automatic API Documentation Generator",
        tools=[
            MCPTool(
                name="generate_openapi",
                description="Generate OpenAPI spec from code",
                parameters={"source_dir": "str"},
                example_usage='generate_openapi(source_dir="./src")'
            ),
            MCPTool(
                name="generate_postman",
                description="Generate Postman collection",
                parameters={"openapi_file": "str"},
                example_usage='generate_postman(openapi_file="openapi.json")'
            ),
        ],
        language="python"
    ),
]


# Global builder instance
_builder = MCPServerBuilder()


def get_mcp_builder() -> MCPServerBuilder:
    """Get the global MCP builder instance"""
    return _builder


def get_example_specs() -> List[MCPServerSpec]:
    """Get example MCP server specs"""
    return EXAMPLE_SPECS


# Made with Bob